#!/usr/bin/env bash
#
# init-skeleton.sh — ensure the dev-WHMCS test environment exists.
#
# Idempotent; call it at the start of any test run. It:
#   1. ensures partnerApiKey / partnerApiSecret / testClientPassword exist in
#      <Vh root>/.user/whmcs/secrets-dev.json (generates them on first run)
#   2. uploads skeleton.php + fixtures.json to the dev box and runs it there
#      (direct-DB, create-if-missing — see fixtures.json for what it ensures)
#   3. regenerates tests/integration/.env from secrets-dev.json
#
# Env overrides: WHMCS_DEV_SSH_KEY, WHMCS_DEV_SSH_HOST, WHMCS_DEV_URL

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
VH_ROOT="$(cd "$REPO_ROOT/.." && pwd)"

SSH_KEY="${WHMCS_DEV_SSH_KEY:-$VH_ROOT/.user/whmcs/ssh.openssh}"
SSH_HOST="${WHMCS_DEV_SSH_HOST:-whmcsdev@webhost-ftps.vpnhood.com}"
SITE_URL="${WHMCS_DEV_URL:-https://whmcs-dev.vpnhood.com}"
SECRETS="$VH_ROOT/.user/whmcs/secrets-dev.json"

[ -f "$SSH_KEY" ] || { echo "SSH key not found: $SSH_KEY" >&2; exit 1; }
[ -f "$SECRETS" ] || { echo "secrets file not found: $SECRETS" >&2; exit 1; }
SSH=(ssh -i "$SSH_KEY" -o BatchMode=yes -o ConnectTimeout=15 "$SSH_HOST")

# node needs a Windows-style path under Git Bash
SECRETS_NODE="$SECRETS"
command -v cygpath >/dev/null 2>&1 && SECRETS_NODE="$(cygpath -m "$SECRETS")"

echo "== Ensuring test credentials in secrets-dev.json"
SECRETS_PATH="$SECRETS_NODE" node <<'EOF'
const fs = require('fs'), crypto = require('crypto');
const p = process.env.SECRETS_PATH;
const s = JSON.parse(fs.readFileSync(p, 'utf8'));
const rnd = (n) => crypto.randomBytes(n).toString('base64url');
let changed = false;
if (!s.partnerApiKey)      { s.partnerApiKey = 'vhtest_' + rnd(21); changed = true; }
if (!s.partnerApiSecret)   { s.partnerApiSecret = rnd(36);          changed = true; }
if (!s.testClientPassword) { s.testClientPassword = 'Vh.' + rnd(12); changed = true; }
if (changed) fs.writeFileSync(p, JSON.stringify(s, null, 2) + '\n');
console.log(changed ? '   generated missing test credentials' : '   all present');
EOF

secret() { SECRETS_PATH="$SECRETS_NODE" KEY_NAME="$1" node -p 'require(process.env.SECRETS_PATH)[process.env.KEY_NAME]'; }
PARTNER_API_KEY="$(secret partnerApiKey)"
PARTNER_API_SECRET="$(secret partnerApiSecret)"
TEST_CLIENT_PASSWORD="$(secret testClientPassword)"

echo "== Running skeleton on the dev box"
"${SSH[@]}" 'mkdir -p ~/tmp'
scp -i "$SSH_KEY" -q "$SCRIPT_DIR/skeleton.php" "$SCRIPT_DIR/fixtures.json" "$SSH_HOST":tmp/
"${SSH[@]}" "TEST_CLIENT_PASSWORD=$(printf %q "$TEST_CLIENT_PASSWORD") \
  PARTNER_API_KEY=$(printf %q "$PARTNER_API_KEY") \
  PARTNER_API_SECRET=$(printf %q "$PARTNER_API_SECRET") \
  php ~/tmp/skeleton.php ~/tmp/fixtures.json; rc=\$?; rm -f ~/tmp/skeleton.php ~/tmp/fixtures.json; exit \$rc"

echo "== Writing tests/integration/.env"
cat > "$REPO_ROOT/tests/integration/.env" <<ENV
# Generated by tests/bootstrap/init-skeleton.sh — do not commit; edits are overwritten.
HUB_URL=$SITE_URL
HUB_KEY=$PARTNER_API_KEY
HUB_SECRET=$PARTNER_API_SECRET
HUB_DOWNSTREAM_REF=reseller-one-month-premium-code
# Set to 1 to run the order/lifecycle flow (spends reseller credit, provisions a real key)
HUB_RUN_PROVISION=${HUB_RUN_PROVISION:-0}
ENV

echo "Skeleton OK"
